name: Build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Test
        run: npm run test
      - name: Setup Node for publish
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://npm.pkg.github.com"
      - name: Publish to GitHub Packages
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
